import '../styles/globals.css'
import type {AppProps} from 'next/app'
import Head from 'next/head';
import Script from "next/script";
import React from "react";
// import Script from 'next/script';
//
// import {TrackingHeadScript} from "@phntms/next-gtm";

function MyApp({Component, pageProps}: AppProps) {


  return (
    <>
      <Head>
        <title>Adopt</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Script id="gtag" strategy="afterInteractive" dangerouslySetInnerHTML={{
        __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
                new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
                j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
                'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
                })(window,document,'script','dataLayer','GTM-TTM6JWC');`
      }}></Script>
      {/*<Script*/}
      {/*  id="gtag"*/}
      {/*  strategy="afterInteractive"*/}
      {/*  dangerouslySetInnerHTML={{*/}
      {/*    __html: `*/}
      {/*      window.dataLayer = window.dataLayer || [];*/}
      {/*      function gtag(){dataLayer.push(arguments);}*/}
      {/*      (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':*/}
      {/*                new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],*/}
      {/*                j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=*/}
      {/*                'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);*/}
      {/*                })(window,document,'script','dataLayer','GTM-TTM6JWC');`,*/}
      {/*  }}*/}
      {/*/>*/}
{/*      <Script id="gtag" strategy="afterInteractive" dangerouslySetInnerHTML={{*/}
{/*        __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':*/}
{/*new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],*/}
{/*j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=*/}
{/*'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);*/}
{/*})(window,document,'script','dataLayer','GTM-TTM6JWC');`*/}
{/*      }}></Script>*/}
      {/*<TrackingHeadScript id={'GTM-TTM6JWC'} />*/}
      <Component {...pageProps} />
    </>
  )
}

export default MyApp
