import '../styles/globals.css'
import type {AppProps} from 'next/app'
import Head from 'next/head';
import {useEffect} from "react";

import * as gtag from '../lib/gtag'
import Analytics from '../components/Analytics'
import {useRouter} from "next/router";

function MyApp({Component, pageProps}: AppProps) {
  const router = useRouter()

  useEffect(() => {
    const handleRouteChange = (url: any) => {
      gtag.pageview(url)
    }
    router.events.on('routeChangeComplete', handleRouteChange)
    return () => {
      router.events.off('routeChangeComplete', handleRouteChange)
    }
  }, [router.events])

  return (
    <>
      <Head>
        <title>Adopt</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Component {...pageProps} />
      <Analytics/>
    </>
  )
}

export default MyApp
