import '../styles/globals.css'
import type {AppProps} from 'next/app'
import Head from 'next/head';
import React from "react";


function MyApp({Component, pageProps}: AppProps) {
  return (
    <>
      <Head>
        <title>Adopt</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Component {...pageProps} />
    </>
  )
}

export default MyApp
